Default: &defaults
  database: smallEmail.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: smallEmail_test.sqlite3
  <<: *defaults

Staging:
  database: smallEmail_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: smallEmail_production.sqlite3
  poolsize: 100
  <<: *defaults
